version: "3.8"

services:
  tulipana-dev:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tulipana-dev
    ports:
      - "3000:3000"
    env_file:
      - .env.local
    volumes:
      - .:/usr/src/app
      - node_modules:/usr/src/app/node_modules
    command: npm run dev
    environment:
      - NODE_ENV=development
      - CHROMA_HOST=chromadb
      - CHROMA_PORT=8000
    depends_on:
      - chromadb

  chromadb:
    image: chromadb/chroma:latest
    container_name: chromadb-dev
    ports:
      - "8000:8000"
    volumes:
      - chroma_data_dev:/chroma/.chroma/index

volumes:
  chroma_data_dev:
  node_modules:
