version: "3.8"

services:
  tulipana-prod:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tulipana-prod
    ports:
      - "3000:3000"
    env_file:
      - .env.production
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - CHROMA_HOST=chromadb
      - CHROMA_PORT=8000
    depends_on:
      - chromadb

  chromadb:
    image: chromadb/chroma:latest
    container_name: chromadb-prod
    ports:
      - "8000:8000"
    volumes:
      - chroma_data_prod:/data

volumes:
  chroma_data_prod:
