version: "3.8"

services:
  tulipana-prod:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tulipana-prod
    ports:
      - "3000:3000"
    env_file:
      - .env.production
    restart: unless-stopped
    environment:
      - NODE_ENV=production
